force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Price</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/showOpportunityController.cls
public with sharing class showOpportunityController {
    
    @AuraEnabled(cacheable = true)
    public static List<Opportunity> getOpportunities() {
        return [SELECT id, Name, Amount, StageName, CloseDate, (SELECT id, Name, Quantity__c, Price__c FROM Products__r) 
                FROM Opportunity];
    }

    // @AuraEnabled(cacheable = true)
    // public static List<Product__c> getProducts(List<Id> opportunityIds) {
    //     return [SELECT Id, Name, Quantity__c, Price__c, Opportunity__c 
    //             FROM Product__c WHERE Opportunity__c IN :opportunityIds];
    // }
}